---
- hosts: all
  become: yes
  become_user: root

  tasks:
    - name: DNF Packages
      include_tasks: "tasks/dnf-packages.yml"

    - name: Firewall
      include_tasks: "./tasks/firewalld.yml"

    - name: SELinux
      include_tasks: "./tasks/selinux.yml"

    - name: Helm3
      include_tasks: "./tasks/helm3.yml"

    - name: kfreestyle2d
      include_tasks: "./tasks/kfreestyle2d.yml"

    - name: GitKraken
      include_tasks: "./tasks/gitkraken.yml"

    - name: Git Config
      include_tasks: "./tasks/gitconfig.yml"

    - name: JetBrains Toolbox
      include_tasks: "./tasks/jetbrains-toolbox.yml"

    - name: Zoom
      include_tasks: "./tasks/zoom.yml"

    - name: GlobalProtect VPN Client
      debug:
        msg: |
          Visit https://software-catalog.app.utah.edu to order and download the Employee-licensed GlobalProtect VPN Client.

  handlers:
#    - name: Clean DNF Caches
#      shell: >-
#        dnf clean all
#      listen: clean_dnf_all
