---
- hosts: all
  become: yes
  become_user: root

  tasks:
    - name: DNF Packages
      include_tasks: "tasks/dnf-packages.yml"

    - name: Firewall
      include_tasks: "./tasks/firewalld.yml"

    - name: SELinux
      include_tasks: "./tasks/selinux.yml"

    - name: Helm3
      include_tasks: "./tasks/helm3.yml"
