---
- hosts: all
  become: yes

  tasks:
    - name: DNF Packages
      include_tasks: "tasks/dnf-packages.yml"

    - name: X.Org Server
      include_tasks: "tasks/xorg.yml"

    - name: Xfce4
      include_tasks: "tasks/xfce4/xfce4.yml"

    - name: Bash shell config
      include_tasks: "tasks/bashrc.yml"

    - name: Firewall
      include_tasks: "tasks/firewalld.yml"

    - name: SELinux
      include_tasks: "tasks/selinux.yml"

    - name: SSH Config
      include_tasks: "tasks/sshconfig.yml"

    - name: Conda
      include_tasks: "tasks/conda.yml"

    - name: Helm
      include_tasks: "tasks/helm.yml"

    - name: variantdev/vals
      include_tasks: "tasks/variantdev-vals.yml"

    - name: kfreestyle2d
      include_tasks: "tasks/kfreestyle2d.yml"

    - name: GitKraken
      include_tasks: "tasks/gitkraken.yml"

    - name: Git Config
      include_tasks: "tasks/gitconfig.yml"

    - name: JetBrains Toolbox
      include_tasks: "tasks/jetbrains-toolbox.yml"

    - name: Zoom
      include_tasks: "tasks/zoom.yml"

    - name: Assorted scripts
      include_tasks: "tasks/scripts.yml"

    - name: GlobalProtect VPN Client
      debug:
        msg: |
          Visit https://software-catalog.app.utah.edu to order and download the Employee-licensed GlobalProtect VPN Client.
#
#  handlers:
#    - name: Clean DNF Caches
#      shell: >-
#        dnf clean all
#      listen: clean_dnf_all
