---

- name: Add Git branch to Bash prompt
  blockinfile:
    path: '$HOME/.bashrc'
    block: |
      # Git
      parse_git_branch() {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
      }
      
      export PS1="\u@\h \[\033[32m\]\w\[\033[1;31m\]\$(parse_git_branch)\[\033[00m\]\n$ "
    state: present
    validate: 'bash -n %s'
  become_user: "{{ ansible_user }}"

- name: Add USE_GKE_GCLOUD_AUTH_PLUGIN to Bash
  blockinfile:
    path: '$HOME/.bashrc'
    block: |
      # gcloud options
      USE_GKE_GCLOUD_AUTH_PLUGIN=True
    state: present
    validate: 'bash -n %s'
  become_user: "{{ ansible_user }}"

- name: Install Kubectl Bash autocomplete
  blockinfile:
    path: '$HOME/.bashrc'
    block: |
      # kubectl bash completion
      source <(kubectl completion bash)
    state: present
    validate: 'bash -n %s'
  become_user: "{{ ansible_user }}"

- name: Install Terraform Bash autocomplete
  blockinfile:
    path: '$HOME/.bashrc'
    block: |
      # terraform bash completion
      complete -C /usr/bin/terraform terraform
    state: present
    validate: 'bash -n %s'
  become_user: "{{ ansible_user }}"

- name: Install Vagrant Bash autocomplete
  shell: >-
    vagrant autocomplete install --bash
  become_user: "{{ ansible_user }}"