---

- name: Extra Packages for Enterprise Linux (EPEL)
  dnf:
    name:
      - epel-release
    state: present

- name: Enable EPEL group
  shell: >-
    dnf --enablerepo=epel group

- name: Install/update system-related packages
  dnf:
    name:
      - bash-completion
      - dnf-plugins-core
      - firewalld
      - sshpass
    state: latest

- name: Install/update system-related modules
  dnf:
    name:
      - "@base-x"
      - "@Container management"
      - "@Development tools"
      - "@Xfce"
    state: latest

- name: Install/update kernel-related packages
  dnf:
    name:
      - dkms
      - kernel-devel-{{ ansible_kernel }}
      - kernel-headers-{{ ansible_kernel }}
    state: latest

- name: Add other package repo files
  template:
    src: "templates/yum.repos.d/{{ item }}.j2"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - 1password.repo
    - conda.repo
    - google-chrome.repo
    - google-cloud-sdk.repo
    - hashicorp.repo
    - nvidia-cuda.repo
    - slack.repo
    - virtualbox.repo
    - vscode.repo

- name: Import rpm keys
  rpm_key:
    state: present
    key: "{{ item }}"
  loop:
#    - "{{ conda_rpm_key }}"
    - "{{ ghcli_rpm_key }}"
    - "{{ googlechrome_rpm_key }}"
    - "{{ googlecloudsdk_rpm_key }}"
    - "{{ googlecloudsdk_yum_key }}"
    - "{{ hashicorp_rpm_key }}"
    - "{{ nvidia_cuda_rhel9_rpm_key }}"
    - "{{ onepassword_rpm_key }}"
#    - "{{ slack_rpm_key }}"
    - "{{ virtualbox_rpm_key }}"
    - "{{ vscode_rpm_key }}"
    - "{{ zoom_prpm_key }}"

- name: Install/update display-related packages
  dnf:
    name:
      - cuda-drivers.x86_64
      - nvidia-driver.x86_64
      - nvidia-settings.x86_64
    state: latest

- name: Install/update gui-related packages
  dnf:
    name:
      - gnome-theme-extras
      - papirus-icon-theme
      - xfce4-about.x86_64
      - xfce4-screenshooter.x86_64
      - xfce4-whiskermenu-plugin.x86_64
    state: latest

- name: Install/update kubectl & Google Cloud SDK
  dnf:
    name:
      - google-cloud-sdk
      - kubectl-{{ kubectl_version }}
    state: latest

- name: Install/update Google Cloud SDK components
  dnf:
    name:
      - google-cloud-sdk-{{ item }}
    state: latest
  loop: "{{ googlecloudsdk_components | dict2items }}"

- name: Install extra containerization packages
  dnf:
    name:
      - podman
      - podman-compose
    state: latest

- name: Install VirtualBox
  dnf:
    name:
      - VirtualBox-{{ virtualbox_version }}
    state: present

- name: Install/update GitKraken
  dnf:
    name: https://release.axocdn.com/linux/gitkraken-amd64.rpm
    disable_gpg_check: yes
    state: present

- name: Install/update Zoom
  dnf:
    name: https://zoom.us/client/latest/zoom_x86_64.rpm
#    disable_gpg_check: yes
    state: present

- name: Install/update other packages
  dnf:
    name:
      - 1password
      - code
      - conda
      - firefox
      - gh
      - git
      - google-chrome-stable
      - keepassxc
      - slack
      - terraform
      - vagrant
      - wireshark
    state: latest
