---

- name: Extra Packages for Enterprise Linux (EPEL)
  dnf:
    name:
      - epel-release
    state: present

- name: Add Rocky PowerTools repo
  shell: >-
    dnf config-manager --set-enabled powertools

- name: Add other package repo files
  template:
    src: "templates/yum.repos.d/{{ item }}.j2"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - 1password.repo
    - conda.repo
    - google-chrome.repo
    - google-cloud-sdk.repo
    - hashicorp.repo
    - kubernetes.repo
    - nvidia-cuda.repo
    - slack.repo
    - virtualbox.repo
    - vscode.repo

- name: Import rpm keys
  rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - "{{ conda_rpm_key }}"
    - "{{ googlechrome_rpm_key }}"
    - "{{ googlecloudsdk_rpm_key }}"
    - "{{ googlecloudsdk_yum_key }}"
    - "{{ hashicorp_rpm_key }}"
    - "{{ nvidia_cuda_rhel8_rpm_key }}"
    - "{{ nvidia_cuda_rhel9_rpm_key }}"
    - "{{ onepassword_rpm_key }}"
    - "{{ slack_rpm_key }}"
    - "{{ virtualbox_rpm_key }}"
    - "{{ vscode_rpm_key }}"

- name: Install DNF modules
  dnf:
    name:
      - "@base-x"
      - "@Container management"
      - "@Development tools"
      - "@nvidia-driver:latest-dkms"
      - "@Xfce"
    state: present

- name: Install System-related packages
  dnf:
    name:
      - bash-completion
      - dnf-plugins-core
      - cuda
      - firewalld
      - kernel-devel-{{ ansible_kernel }}
      - kernel-headers-{{ ansible_kernel }}
      - sshpass
      - xfce4-about.x86_64
      - xfce4-clipman-plugin.x86_64
      - xfce4-screenshooter.x86_64
      - xfce4-whiskermenu-plugin.x86_64
    state: present

- name: Install Web Browsers
  dnf:
    name:
      - google-chrome-stable
      - firefox
    state: present

- name: Install Kubectl & Google Cloud SDK components
  dnf:
    name:
      - google-cloud-sdk
      - google-cloud-sdk-gke-gcloud-auth-plugin
      - google-cloud-sdk-minikube
      - kubectl-{{ kubectl_version }}
    state: present

- name: Install extra containerization tools
  dnf:
    name:
      - podman-compose
    state: present

- name: Install other apps
  dnf:
    name:
      - 1password
      - code
      - conda
      - git
      - keepassxc
      - slack
      - terraform
      - vagrant
      - wireshark
      - VirtualBox-{{ virtualbox_version }}
    state: present
