---

- name: Extra Packages for Enterprise Linux (EPEL)
  dnf:
    name:
      - epel-release
    state: present

- name: Add Rocky PowerTools repo
  shell: >-
    dnf config-manager --set-enabled powertools

- name: Add other package repo files
  template:
    src: "templates/yum.repos.d/{{ item }}.j2"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - 1password.repo
    - google-chrome.repo
    - google-cloud-sdk.repo
    - hashicorp.repo
    - kubernetes.repo
    - nvidia-cuda.repo
    - slack.repo
    - virtualbox.repo
    - vscode.repo

- name: Import rpm keys
  rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ onepassword_rpm_key }}"
    - "{{ googlechrome_rpm_key }}"
    - "{{ googlecloudsdk_rpm_key }}"
    - "{{ googlecloudsdk_yum_key }}"
    - "{{ hashicorp_rpm_key }}"
    - "{{ kubernetes_rpm_key }}"
    - "{{ kubernetes_yum_key }}"
    - "{{ nvidia_cuda_rhel8_rpm_key }}"
    - "{{ nvidia_cuda_rhel9_rpm_key }}"
    - "{{ slack_rpm_key }}"
    - "{{ virtualbox_rpm_key }}"
    - "{{ vscode_rpm_key }}"

- name: Install DNF modules
  dnf:
    name:
      - "@Development tools"
      - "@nvidia-driver:latest-dkms"
    state: present

- name: Install DNF packages
  dnf:
    name:
      - 1password
      - dnf-plugins-core
      - code
      - cuda
      - firefox
      - firewalld
      - git
      - google-chrome-stable
      - google-cloud-sdk
      - google-cloud-sdk-gke-gcloud-auth-plugin
      - google-cloud-sdk-minikube
      - kernel-devel-{{ ansible_kernel }}
      - kernel-headers-{{ ansible_kernel }}
      - kubectl-{{ kubectl_version }}
      - podman
      - podman-compose
      - slack
      - terraform
      - which
      - vagrant
      - VirtualBox-{{ virtualbox_version }}
    state: present
