---

- name: Add system-wide gitignore
  template:
    src: 'templates/gitignore.j2'
    dest: '/etc/gitignore'
    owner: root
    group: root
    mode: '0644'

- name: Add gitconfig pull.ff system-wide
  community.general.git_config:
    name: pull.ff
    scope: system
    value: only

- name: Add gitconfig core.excludesfile system-wide
  community.general.git_config:
    name: core.excludesfile
    scope: system
    value: /etc/gitignore

- name: "Add gitconfig user.email globally for {{ local_user }}"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ local_user_email }}"
  become_user: "{{ local_user }}"

- name: "Add gitconfig user.name globally for {{ local_user }}"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ local_user_name }}"
  become_user: "{{ local_user }}"

- name: "Add gitconfig user.signingkey globally for {{ local_user }}"
  community.general.git_config:
    name: user.signingkey
    scope: global
    value: "{{ local_user_gpg_key }}"
  become_user: "{{ local_user }}"

- name: "Add gitconfig commit.gpgsign globally for {{ local_user }}"
  community.general.git_config:
    name: commit.gpgsign
    scope: global
    value: true
  become_user: "{{ local_user }}"

- name: "Add gitconfig tag.forcesignannotated globally for {{ local_user }}"
  community.general.git_config:
    name: tag.forcesignannotated
    scope: global
    value: true
  become_user: "{{ local_user }}"
