---
- name: Checking if GitKraken install directory already exists
  stat:
    path: '/usr/bin/gitkraken'
  register: gitkraken_install_path

- name: Install GitKraken
  dnf:
    name: "{{ gitkraken_rpm }}"
    disable_gpg_check: yes
    state: present
  when: not gitkraken_install_path.stat.exists
