---

- name: "Set up panel dark mode"
  xfconf:
    channel: 'xfce4-panel'
    property: "/panels/dark-mode"
    value_type: bool
    value: true
  become_user: "{{ local_user }}"

- name: "Set up panel background style"
  xfconf:
    channel: 'xfce4-panel'
    property: "/panels/panel-{{ item }}/background-style"
    value_type: int
    value: 0
  loop:
    - 1
    - 2
    - 3
  become_user: "{{ local_user }}"

- name: "Set up panel icon size"
  xfconf:
    channel: 'xfce4-panel'
    property: "/panels/panel-{{ item }}/icon-size"
    value_type: int
    value: 0
  loop:
    - 1
    - 2
    - 3
  become_user: "{{ local_user }}"

- name: "Set up panel length"
  xfconf:
    channel: 'xfce4-panel'
    property: "/panels/panel-{{ item }}/length"
    value_type: int
    value: 100
  loop:
    - 1
    - 2
    - 3
  become_user: "{{ local_user }}"

- name: "Set up panel mode"
  xfconf:
    channel: 'xfce4-panel'
    property: "/panels/panel-{{ item }}/mode"
    value_type: int
    value: 0
  loop:
    - 1
    - 2
    - 3
  become_user: "{{ local_user }}"

- name: "Set up panel position locked"
  xfconf:
    channel: 'xfce4-panel'
    property: "/panels/panel-{{ item }}/position-locked"
    value_type: bool
    value: true
  loop:
    - 1
    - 2
    - 3
  become_user: "{{ local_user }}"

- name: "Set up panel size"
  xfconf:
    channel: 'xfce4-panel'
    property: "/panels/panel-{{ item }}/size"
    value_type: int
    value: 32
  loop:
    - 1
    - 2
    - 3
  become_user: "{{ local_user }}"

- name: "Set up panel output-names"
  xfconf:
    channel: 'xfce4-panel'
    property: "/panels/panel-{{ item.key }}/output-name"
    value_type: string
    value: "{{ item.value }}"
  loop: "{{ panel_data | dict2items }}"
  vars:
    panel_data:
      1: 'DP-0.8'
      2: 'DP-2.8'
      3: 'DP-4'
  become_user: "{{ local_user }}"

- name: "Set up panel plugin ids"
  xfconf:
    channel: 'xfce4-panel'
    property: "/panels/panel-{{ item.key }}/plugin-ids"
    value_type: string
    value: "{{ item.value }}"
  loop: "{{ panel_data | dict2items }}"
  vars:
    panel_data:
      1: ['7', '23', '9', '1', '15', '2', '3', '4', '5', '6', '8', '11', '12', '13', '22']
      2: ['24', '16', '18', '19', '17', '20', '21']
      3: ['10', '25', '26']
  become_user: "{{ local_user }}"

- name: "Set up plugin types"
  xfconf:
    channel: 'xfce4-panel'
    property: "/plugins/plugin-{{ item.key }}"
    value_type: string
    value: "{{ item.value }}"
  loop: "{{ plugin_data | dict2items }}"
  vars:
    plugin_data:
      1: 'launcher'
      2: 'tasklist'
      3: 'separator'
      4: 'pager'
      5: 'separator'
      6: 'systray'
      7: 'whiskermenu'
      8: 'pulseaudio'
      9: 'launcher'
      10: 'tasklist'
      11: 'separator'
      12: 'clock'
      13: 'separator'
      15: 'launcher'
      16: 'separator'
      17: 'clock'
      18: 'pager'
      19: 'separator'
      20: 'separator'
      21: 'showdesktop'
      22: 'showdesktop'
      23: 'separator'
      24: 'tasklist'
      25: 'separator'
      26: 'clock'
  become_user: "{{ local_user }}"

- name: "Set up panel separators expand"
  xfconf:
    channel: 'xfce4-panel'
    property: "/plugins/plugin-{{ item }}/expand"
    value_type: bool
    value: true
  loop:
    - 3
    - 16
    - 25
  become_user: "{{ local_user }}"

- name: "Set up panel tasklist include-all-monitors"
  xfconf:
    channel: 'xfce4-panel'
    property: "/plugins/plugin-{{ item }}/include-all-monitors"
    value_type: bool
    value: false
  loop:
    - 2
    - 10
    - 24
  become_user: "{{ local_user }}"

- name: "Set up panel clock datetime displays"
  xfconf:
    channel: 'xfce4-panel'
    property: "/plugins/plugin-{{ item }}/digital-format"
    value_type: string
    value: "%A %B %_d, %l:%M %p"
  loop:
    - 12
    - 17
    - 26
  become_user: "{{ local_user }}"

- name: "Set up panel clock timezones"
  xfconf:
    channel: 'xfce4-panel'
    property: "/plugins/plugin-{{ item }}/timezone"
    value_type: string
    value: "America/Denver"
  loop:
    - 12
    - 17
    - 26
  become_user: "{{ local_user }}"

- name: "Set up panel pager rows"
  xfconf:
    channel: 'xfce4-panel'
    property: "/plugins/plugin-{{ item }}/pager"
    value_type: int
    value: 2
  loop:
    - 4
    - 18
  become_user: "{{ local_user }}"

- name: "Ensure xfce4 panel directory exists for {{ local_user }}"
  file:
    path: "$HOME/.config/xfce4/panel"
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: 0755
  become_user: "{{ local_user }}"

- name: "Verify whiskermenu config for {{ local_user }} is present"
  file:
    path: '$HOME/.config/xfce4/panel/whiskermenu-7.rc'
    state: touch
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: 0664
    modification_time: preserve
    access_time: preserve
  become_user: "{{ local_user }}"

- name: "Add settings to whiskermenu config for {{ local_user }}"
  blockinfile:
    path: '$HOME/.config/xfce4/panel/whiskermenu-7.rc'
    block: |
      favorites={{ xfce4_whiskermenu_favorites }}
      button-title={{ xfce4_whiskermenu_title }}
      button-icon=system-logo-icon
      button-single-row=false
      show-button-title=true
      show-button-icon=true
      launcher-show-name=true
      launcher-show-description=true
      launcher-show-tooltip=false
      item-icon-size=4
      hover-switch-category=false
      category-show-name=true
      category-icon-size=0
      load-hierarchy=false
      view-as-icons=true
      default-category=0
      recent-items-max=10
      favorites-in-recent=true
      position-search-alternate=true
      position-commands-alternate=false
      position-categories-alternate=true
      stay-on-focus-out=false
      confirm-session-command=true
      menu-width=670
      menu-height=574
      menu-opacity=100
      command-settings=xfce4-settings-manager
      show-command-settings=true
      command-lockscreen=xflock4
      show-command-lockscreen=true
      command-switchuser=gdmflexiserver
      show-command-switchuser=false
      command-logoutuser=xfce4-session-logout --logout --fast
      show-command-logoutuser=false
      command-restart=xfce4-session-logout --reboot --fast
      show-command-restart=true
      command-shutdown=xfce4-session-logout --halt --fast
      show-command-shutdown=true
      command-suspend=xfce4-session-logout --suspend
      show-command-suspend=false
      command-hibernate=xfce4-session-logout --hibernate
      show-command-hibernate=false
      command-logout=xfce4-session-logout
      show-command-logout=true
      command-menueditor=menulibre
      show-command-menueditor=true
      command-profile=mugshot
      show-command-profile=true
      search-actions=5
    state: present
  become_user: "{{ local_user }}"

- name: "Download Whiskermenu ~/.face for {{ local_user }}"
  get_url:
    url: "{{ xfce4_whiskermenu_face }}"
    dest: "$HOME/.face"
    mode: '0664'
  become_user: "{{ local_user }}"