---

- name: "Set workspace names"
  xfconf:
    channel: 'xfwm4'
    property: '/general/workspace_names'
    value_type: string
    value: ['Primus', 'Secundus']
  become_user: "{{ ansible_user }}"
