---

- name: "Set up 'IconThemeName' xsettings"
  xfconf:
    channel: 'xsettings'
    property: "/Net/IconThemeName"
    value_type: string
    value: "Adwaita"
  become_user: "{{ local_user }}"

- name: "Set up 'ThemeName' xsettings"
  xfconf:
    channel: 'xsettings'
    property: "/Net/ThemeName"
    value_type: string
    value: "Adwaita-dark"
  become_user: "{{ local_user }}"
